- README.zh-tw.md
- app/build.gradle
- app/src/main/res/values-zh-rTW/strings.xml
With a translated README.md including the Play store intro.
> Traditional Chinese translation init upload.

- app/build.gradle
- app/src/main/res/values-fr-rFR/strings.fr-rFR.xml
> french translation

- app/src/main/res/values-ru/strings.xml
Опечатки в двух словах: "найдеи" и "устойства"
> Исправление опечаток.

- app/src/main/res/values-pl/strings.xml
Please, update the translation.
> Update the translation

- app/src/main/res/values/strings.xml
It is a language update for the String file. Hindi is the National language of India.
> Hindi Version update for ScreenStream strings

- data/src/main/res/values-de/strings.xml
> Added German translation

- data/src/main/res/values-de/strings.xml
I updated it so it should be ok now.
> Updated German translation

- app/src/main/res/values-sk/strings.xml
- data/src/main/res/values-sk/strings.xml
Added 2 files:
- app/src/main/res/values-sk/strings.xml and
- data/src/main/res/values-sk/strings.xml
Is everything OK to merge, or should i do something more?
> Added slovak language (slovenčina)

- README.md
How to add a new translation...
> readme.md - added Contribution part

- app/src/main/res/values-ar/strings.xml
There was some issues with the RTL translation in arabic language
> fixing some issue in the arabic translation and RTL translation

- app/src/main/AndroidManifest.xml
- app/src/main/kotlin/info/dvkr/screenstream/di/BaseKoinModule.kt
- app/src/main/kotlin/info/dvkr/screenstream/service/AppService.kt
- app/src/main/kotlin/info/dvkr/screenstream/service/helper/QuickSettingsHelper.kt
This feature is targeting Android nougat devices. the Quick settings tile will function as start / stop streaming button for quick access.
>  Resolves #15 : add quick settings tile for start|stop streaming

- app/build.gradle
- app/src/main/res/values-cat/strings.xml
- data/src/main/res/values-cat/strings.xml
The Catalan language is spoken by more than 10 million people worldwide. It is spoken in Italy, France, Iberia, Spain, Andorra and many other places.
Learn more at the link: [https://en.wikipedia.org/wiki/Catalan_language](https://en.wikipedia.org/wiki/Catalan_language)
> Added Catalan translation

- app/build.gradle
I'm sorry dkrivoruchko, the Galician language code is "gl". I didn't pay any attention to that, but I'm already sending the solution.
> Solution in the error I made with the code of the Galician language.

- app/src/main/res/values-cat/strings.xml
Added \ before apostrophes, to stop warnings.
> Problem with apostrophes in translation solved

- data/src/main/kotlin/com/android/grafika/gles/Drawable2d.java
- data/src/main/kotlin/com/android/grafika/gles/EglCore.java
- data/src/main/kotlin/com/android/grafika/gles/EglSurfaceBase.java
- data/src/main/kotlin/com/android/grafika/gles/FullFrameRect.java
- data/src/main/kotlin/com/android/grafika/gles/GlUtil.java
- data/src/main/kotlin/com/android/grafika/gles/OffscreenSurface.java
- data/src/main/kotlin/com/android/grafika/gles/Texture2dProgram.java
- data/src/main/kotlin/info/dvkr/screenstream/data/image/BitmapCapture.kt
Tried to use the app on my Samsung N8010 tablet running LineageOS 14.1 but failed due to the „unknown format“ problem.
Did some research and found out that the ImageReader approach will fail when the producer's pixel format is not supported by ImageReader (as is the case for BGRA_8888 / 0x5, which is used by my device). Thankfully, I stumbled upon [a solution on StackExchange](https://stackoverflow.com/a/34741581) using OpenGL, making use of some classes from [Google's Grafika project](https://github.com/google/grafika) which I then successfully built into the BitmapCapture class as a fallback so now the app is working on my tablet and I can use it for streaming my screen to Zoom since normal screen share won't work as their app seems to trip over the pixel format, too. Great app, 5/5! I …
> fixed “unknown format” problem

- app/src/main/res/values-pt-rBR/strings.xml
> updated missing strings

- app/src/main/res/values-pt-rBR/strings.xml
- data/src/main/res/values-pt-rBR/strings.xml
> updated strings

- app/src/main/res/values/strings.xml
- data/src/main/res/values/strings.xml
Translated to spoken Ukrainian language.
> UA translation

- app/src/main/res/values-zh/strings.xml
- mjpeg/src/main/res/values-zh/strings.xml
updated strings.xml in mjpeg and app directories.
> Update Simplified Chinese Strings

- app/src/main/res/strings.xml
- mjpeg/src/main/res/strings.xml
- webrtc/src/main/res/strings.xml
Please, add values-eu folder and put loaded strings.xml file in that folder
> Add translation to Basque language (eu)
